repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: '' # Use the sha / tag you want to point at
      hooks:
          - id: prettier
            additional_dependencies:
                - prettier@2.4.1
